### ISSUE TITLE
Dependency on Numpy's C code

### ISSUE THREAD

**Issue by SalvatoreT** [openai/pachi-py#3]
When trying to install `pachi-py` (or `gym` by extension), users hit this error.

```
Failed to load numpy: No module named numpy. Numpy must be already installed to normally set up pachi-py. Trying to actually build pachi-py will result in an error.
Traceback (most recent call last):
  File "setup.py", line 36, in <module>
    include_dirs=[numpy.get_include(), "pachi_py/pachi"],
  File "setup.py", line 7, in get_include
    raise Exception('Tried to compile pachi-py, but numpy is not installed. HINT: Please install numpy separately before attempting this -- `pip install numpy` should do it.')
Exception: Tried to compile pachi-py, but numpy is not installed. HINT: Please install numpy separately before attempting this -- `pip install numpy` should do it.
```

This is a strange error to see, because typically pip installs handle their dependencies for the user. However, because the extension part of the setup.py file has [this one line of code](https://github.com/openai/pachi-py/blob/master/setup.py#L36). The whole setup script breaks.

``` python
# line 36
include_dirs=[numpy.get_include(), "pachi_py/pachi"],
```

The directories from Numpy are required because the [cypachi.cpp](https://github.com/openai/pachi-py/blob/master/pachi_py/cypachi.cpp#L275-L276) file pulls in these two header files so it can use a bunch of Numpy's C structures.

``` cpp
// line 275
#include "numpy/arrayobject.h"
#include "numpy/ufuncobject.h"
```

What would it take to pull the dependency on Numpy's C code and move it to the python level or remove it completely?

**Comment by SalvatoreT** [comment]
Two things:
1) After a bit of digging, it looks like the C++ file I was referencing was auto-generated by [Cython](http://cython.org/).
2) @coldfix already [addressed this Numpy issue on StackOverflow](http://stackoverflow.com/a/21621689/4951255). So, instead of going down the rabbit hole, I decided to do a similar fix.
