### ISSUE TITLE
Path not found on Windows 10

### ISSUE THREAD

**Issue by zimmerrol** [openai/pachi-py#9]
Hello,
while installing `pachi-py` via pip on Windows 10 I get [this ](https://gist.github.com/FlashTek/fc3351b9500b17d0ddea262b48a118de) error message. The German error message `Das System kann den angegebenen Pfad nicht finden.` can be translated with `The system cannot find the path specified`. How do I solve this situation?

**Comment by fmscole** [comment]
系统找不到指定的路径。
  Could not build pachi-py: Command 'cd pachi_py; mkdir -p build && cd build && cmake ../pachi && make -j4' returned non-zero exit status 1.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>

File "c:\anaconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\10471\AppData\Local\Temp\pip-install-r6urbl35\pachi-py\setup.py", line 9, in run
      subprocess.check_call("cd pachi_py; mkdir -p build && cd build && cmake ../pachi && make -j4", shell=True)
    File "c:\anaconda3\lib\subprocess.py", line 291, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'cd pachi_py; mkdir -p build && cd build && cmake ../pachi && make -j4' returned non-zero exit status 1.


Failed to build pachi-py
Installing collected packages: pachi-py
  Running setup.py install for pachi-py ... error
    Complete output from command c:\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\10471\\AppData\\Local\\Temp\\pip-install-r6urbl35\\pachi-py\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\10471\AppData\Local\Temp\pip-record-xigwriaf\install-record.txt --single-version-externally-managed --compile:
    running install

 subprocess.CalledProcessError: Command 'cd pachi_py; mkdir -p build && cd build && cmake ../pachi && make -j4' returned non-zero exit status 1.

    ----------------------------------------
Command "c:\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\10471\\AppData\\Local\\Temp\\pip-install-r6urbl35\\pachi-py\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\10471\AppData\Local\Temp\pip-record-xigwriaf\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\10471\AppData\Local\Temp\pip-install-r6urbl35\pachi-py\

**Comment by zxcvbnm3057** [comment]
Have you fix it? I have a same problem now, and it has been bothering me for a day. I installed VS2019 and Python3.7.2.

**Comment by fmscole** [comment]
> Have you fix it? I have a same problem now, and it has been bothering me for a day. I installed VS2019 and Python3.7.2.

No way to solve the problem!
pachi-py just surport linux.
Give up.

**Comment by zxcvbnm3057** [comment]
> > Have you fix it? I have a same problem now, and it has been bothering me for a day. I installed VS2019 and Python3.7.2.
> 
> No way to solve the problem!
> pachi-py just surport linux.
> Give up.

Thank you.
I tried it on Ubuntu and it works well.
Is there someone made a package for windows?

**Comment by Muhammad19Omer** [comment]
subprocess.CalledProcessError: Command 'cd pachi_py; mkdir -p build && cd build && cmake ../pachi && make -j4' returned non-zero exit status 127.

I am receiving the same error, with the final error: 

error: legacy-install-failure

Can anybody help please?
